# Generated by Django 4.1.7 on 2023-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('fonction', models.CharField(max_length=255, null=True, verbose_name='Fonction')),
                ('objet', models.CharField(max_length=255, null=True, verbose_name='Objet')),
                ('message', models.TextField(null=True, verbose_name='Message')),
            ],
        ),
    ]
