# Generated by Django 4.1.7 on 2023-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activites')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('texte', models.TextField(null=True, verbose_name='Texte')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('texte', models.TextField(null=True, verbose_name='Texte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
