# Generated by Django 4.1.7 on 2023-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_activite_article_contact_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='activites'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='articles'),
        ),
    ]
