# Generated by Django 4.2 on 2023-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_activite_image_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='collapse',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
