# Generated by Django 4.2 on 2023-04-24 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_contact_collapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='collapse',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
