# Generated by Django 4.2 on 2023-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_alter_contact_collapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='vues',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
