# Generated by Django 4.2 on 2023-04-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
