# Generated by Django 4.2 on 2023-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
