# Generated by Django 4.2 on 2023-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_contact_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default='+228 ', max_length=13, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Cochez le message'),
        ),
    ]
