# Generated by Django 4.2 on 2023-04-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_alter_contact_telephone_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
