# Generated by Django 4.2 on 2023-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanniereAccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bannieres/')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.TextField(blank=True, null=True, verbose_name='Libellé bannière')),
                ('voirplus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.TextField(blank=True, null=True, verbose_name='Libellé mission')),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('productivite', models.TextField(blank=True, null=True, verbose_name='Libellé productivite')),
                ('voirplus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jgkec', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.ManyToManyField(blank=True, null=True, to='cabinet.tel')),
            ],
        ),
    ]
