# Generated by Django 4.2 on 2023-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0020_banniereaccueil_date_footer_date_mission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibelleSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='libelle',
        ),
        migrations.AddField(
            model_name='solution',
            name='libelle',
            field=models.ManyToManyField(blank=True, null=True, to='cabinet.libellesolution'),
        ),
    ]
