# Generated by Django 4.2 on 2023-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0025_apropos_alter_footer_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='label',
            field=models.CharField(default='Apropos', max_length=255, null=True),
        ),
    ]
