# Generated by Django 4.2 on 2023-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0028_nossolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nossolutions',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='nossolutions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='imageD',
            field=models.ImageField(blank=True, null=True, upload_to='nossolutions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='imageE',
            field=models.ImageField(blank=True, null=True, upload_to='nossolutions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='imageF',
            field=models.ImageField(blank=True, null=True, upload_to='nossolutions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='imageR',
            field=models.ImageField(blank=True, null=True, upload_to='nossolutions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='voirplusB',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voir plus'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='voirplusD',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voir plus'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='voirplusE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voir plus'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='voirplusF',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voir plus'),
        ),
        migrations.AlterField(
            model_name='nossolutions',
            name='voirplusR',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voir plus'),
        ),
    ]
