# Generated by Django 4.2 on 2023-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0029_alter_nossolutions_imageb_alter_nossolutions_imaged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='titre',
            field=models.TextField(null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.TextField(null=True, verbose_name='Titre'),
        ),
    ]
