# Generated by Django 4.2 on 2023-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0030_alter_activite_titre_alter_article_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activites/')),
                ('titre', models.TextField(blank=True, null=True, verbose_name='Historique des activités')),
                ('texte', models.TextField(null=True, verbose_name='Texte')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('vues', models.IntegerField(default=0, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activites/'),
        ),
    ]
