# Generated by Django 4.1.7 on 2023-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0031_historiqueactivite_alter_activite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='detailproductivite',
            field=models.TextField(blank=True, null=True, verbose_name='Texte sous productivite'),
        ),
    ]
