# Generated by Django 4.1.7 on 2023-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0032_mission_detailproductivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='notreexpertise',
            field=models.TextField(blank=True, null=True, verbose_name='Notre expertise'),
        ),
    ]
