# Generated by Django 4.1.7 on 2023-09-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0033_mission_notreexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Découvrez nos solutions'),
        ),
    ]
