# Generated by Django 4.1.7 on 2023-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0035_mission_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mot_du_dg',
            field=models.TextField(blank=True, null=True, verbose_name='Mot du directeur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='niveau_performance',
            field=models.TextField(blank=True, null=True, verbose_name='Niveau et performance de vos équipes'),
        ),
    ]
