# Generated by Django 4.1.7 on 2023-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0036_mission_mot_du_dg_mission_niveau_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mot_des_clients',
            field=models.TextField(blank=True, null=True, verbose_name='Mot des clients'),
        ),
    ]
