# Generated by Django 4.1.7 on 2023-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0039_remove_expertise_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notremission',
            name='label',
            field=models.CharField(blank=True, default='NotreMission', max_length=255, null=True),
        ),
    ]
