# Generated by Django 4.1.7 on 2023-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0040_alter_notremission_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(default='228xxxxxxxx', max_length=13, null=True, verbose_name='Numéro de téléphone')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
    ]
