# Generated by Django 4.1.7 on 2023-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0047_alter_message_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pays',
            field=models.CharField(max_length=255, null=True, verbose_name='Pays'),
        ),
    ]
