# Generated by Django 4.1.7 on 2024-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0050_alter_elevator_datenaiss_alter_elevator_objectifs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='detail',
            field=models.CharField(choices=[('Réseaux sociaux', 'Réseaux sociaux'), ('Site web JGK-EC', 'Site web JGK-EC'), ('Bouche-à-oreille', 'Bouche-à-oreille'), ('Autre (veuillez préciser)', 'Autre')], max_length=255, null=True, verbose_name='Comment avez-vous entendu parler du Programme Elevator ?'),
        ),
    ]
